# 错误处理

错误处理是指如何捕获和处理同步和异步发生的错误。Express附带了一个默认的错误处理程序，所以您不需要编写自己的错误处理程序。

## 捕获错误

确保Express捕获在运行路由处理程序和中间件时发生的所有错误是非常重要的。

在路由处理程序和中间件中的同步代码中发生的错误不需要额外的工作。如果同步代码抛出错误，Express将捕获并处理它。例如：

```javascript
app.get("/", function (req, res) {
  throw new Error("BROKEN"); // Express自己将捕获这个错误
})
```

对于路由处理程序和中间件调用的异步函数返回的错误，必须将它们传递给 `next()` 函数，Express将在该函数中捕获并处理它们。例如：

```javascript
app.get("/", function (req, res, next) {
  fs.readFile("/file-does-not-exist", function (err, data) {
    if (err) {
      next(err); // Pass errors to Express.
    }
    else {
      res.send(data);
    }
  })
})
```

如果将任何内容传递给next()函数(除了字符串'route')，Express将把当前请求视为错误，并将跳过任何剩余的非错误处理路由和中间件函数。

如果序列中的回调不提供数据，只提供错误，则可以将此代码简化为：

```javascript
app.get("/", [
  function (req, res, next) {
    fs.writeFile("/inaccessible-path", "data", next);
  },
  function (req, res) {
    res.send("OK");
  }
])
```

在上面的例子中，`next` 是作为fs.writeFile的回调函数提供的，不管有没有错误，都会调用。如果没有错误，则执行第二个处理程序，否则捕获并处理错误。

您必须捕获由路由处理程序或中间件调用的异步代码中发生的错误，并将其传递给Express进行处理。例如：

```javascript
app.get("/", function (req, res, next) {

  setTimeout(function () {
    try {
      throw new Error("BROKEN");
    }
    catch (err) {
      next(err);
    }
  }, 100);
});
```

上面的例子使用了一个try…catch块用于捕获异步代码中的错误并将其传递给Express。如果try...catch块忽略了，Express将不会捕获错误，因为它不是同步处理程序代码的一部分。

使用Promises来避免try...catch的开销，或返回Promises时使用函数。例如：

```javascript
app.get("/", function (req, res, next) {
  Promise.resolve().then(function () {
    throw new Error("BROKEN");
  }).catch(next); // Errors will be passed to Express.
});
```

因为Promises会自动捕获同步错误和rejected promises，所以您可以简单地提供 `next` 作为最终的捕获处理程序，Express将捕获错误，因为捕获处理程序将error作为第一个参数。

您还可以使用处理程序链来依赖于同步错误捕获，方法是将异步代码简化为一些简单的东西。例如：

```javascript
app.get("/", [
  function (req, res, next) {
    fs.readFile("/maybe-valid-file", "utf8", function (err, data) {
      res.locals.data = data;
      next(err);
    });
  },
  function (req, res) {
    res.locals.data = res.locals.data.split(",")[1];
    res.send(res.locals.data);
  }
]);
```

上面的例子有几个来自readFile调用的简单语句。如果readFile导致错误，那么它将传递错误给Express，否则您将在链中的下一个处理程序中快速返回同步错误处理。然后，上面的示例尝试处理数据。如果失败，那么同步错误处理程序将捕获它。如果您在readFile回调函数中完成了此处理，那么应用程序可能会退出，Express错误处理程序将不会运行。

无论使用哪种方法，如果希望调用Express错误处理程序并使应用程序存活，都必须确保Express接收到错误。

## 默认错误处理

Express提供了一个内置的错误处理程序，可以处理应用程序中可能遇到的任何错误。这个默认的错误处理中间件函数是在中间件函数栈的末尾添加的。

如果您将一个错误传递给next()，并且您没有在自定义错误处理程序中处理它，那么它将由内置的错误处理程序处理；错误将被写入带有堆栈跟踪的客户机。堆栈跟踪不包括在生产环境中。

> 把NODE_ENV环境变量设置成production来运行生产环境。

如果在开始编写响应之后调用next()时出现错误(例如，如果在将响应流传输到客户机时遇到错误)，Express默认错误处理程序将关闭连接并使请求失败。

因此，在添加自定义错误处理程序时，你必须使用默认的Express错误处理程序，当头部已经被发送到客户端时：

```javascript
function errorHandler (err, req, res, next) {
  if (res.headersSent) {
    return next(err)
  }
  res.status(500)
  res.render('error', { error: err })
}
```

请注意，如果在代码中多次调用next()并出现错误，即使定制的错误处理中间件已经就绪，默认的错误处理程序也会被触发。

## 编写错误处理程序

定义错误处理中间件函数的方式与其他中间件函数相同，除了错误处理函数有四个参数，而不是三个参数:(err, req, res, next)。例如：

```javascript
app.use(function (err, req, res, next) {
  console.error(err.stack)
  res.status(500).send('Something broke!')
})
```

在其他 `app.use()` 和路由调用后面定义错误中间件；例如：

```javascript
var bodyParser = require('body-parser')
var methodOverride = require('method-override')

app.use(bodyParser.urlencoded({
  extended: true
}))
app.use(bodyParser.json())
app.use(methodOverride())
app.use(function (err, req, res, next) {
  // logic
})
```

来自中间件函数的响应可以是任何格式，例如HTML错误页面、简单消息或JSON字符串。

为了组织(和更高层次的框架)的目的，您可以定义几个错误处理中间件函数，就像您可以定义常规中间件函数一样。例如，为使用XHR和不使用XHR的请求定义一个错误处理程序：

```javascript
var bodyParser = require('body-parser')
var methodOverride = require('method-override')

app.use(bodyParser.urlencoded({
  extended: true
}))
app.use(bodyParser.json())
app.use(methodOverride())
app.use(logErrors)
app.use(clientErrorHandler)
app.use(errorHandler)
```

例如，在本例中，通用logErrors可能将请求和错误信息写入 `stderr` ：

```javascript
function logErrors (err, req, res, next) {
  console.error(err.stack)
  next(err)
}
```

在本例中，clientErrorHandler的定义如下：在这种情况下，错误被显式地传递给 `next`。

注意，在错误处理函数中不调用next时，您负责编写(和结束)响应。否则这些请求将"挂起"，并且没有资格进行垃圾收集。

```javascript
function clientErrorHandler (err, req, res, next) {
  if (req.xhr) {
    res.status(500).send({ error: 'Something failed!' })
  } else {
    next(err)
  }
}
```

实现"catch-all" 的errorHandler函数(例如)：

```javascript
function errorHandler (err, req, res, next) {
  res.status(500)
  res.render('error', { error: err })
}
```

如果您有一个路由处理程序中具有多个回调函数，则可以使用route参数跳到下一个路由处理程序。例如：

```javascript
app.get('/a_route_behind_paywall',
  function checkIfPaidSubscriber (req, res, next) {
    if (!req.user.hasPaid) {
      // continue handling this request
      next('route')
    }
    else{
      next();
    }
  }, function getPaidContent (req, res, next) {
    PaidContent.find(function (err, doc) {
      if (err) return next(err)
      res.json(doc)
    })
  })
```

在本例中，getPaidContent处理程序将被跳过，但app中/a_route_behind_paywall中的任何剩余处理程序将继续执行。

> 对next()和next(err)的调用表明当前处理程序已经完成，并且处于什么状态。next(err)将跳过链中所有剩余的处理程序，除了那些设置为处理如上所述的错误的处理程序。
